#ifndef REMUX_FFI_H
#define REMUX_FFI_H

/* Warning: this file is auto-generated by cbindgen. Do not edit. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Initialise FFmpeg. Safe to call multiple times; only the first call has
 * any effect.
 */
void remux_init(void);

/**
 * Return a JSON string containing version information.
 *
 * The caller **must** free the returned string with `remux_free_string`.
 * Returns `NULL` on internal error.
 */
char *remux_version(void);

/**
 * Return a JSON array of third-party license information.
 *
 * The caller **must** free the returned string with `remux_free_string`.
 * Returns `NULL` on internal error.
 */
char *remux_licenses(void);

/**
 * Validate a remux configuration supplied as a JSON string.
 *
 * Returns a JSON string: `{"valid":true}` on success, or
 * `{"valid":false,"error":"..."}` on failure.
 *
 * The caller **must** free the returned string with `remux_free_string`.
 * Returns `NULL` on internal error.
 *
 * # Safety
 *
 * `config_json` must be either null or a valid pointer to a NUL-terminated
 * UTF-8 C string.
 */
char *remux_validate_config(const char *config_json);

/**
 * Process a single `.ubv` file.
 *
 * # Parameters
 *
 * - `ubv_path`          - Path to the `.ubv` file (UTF-8 C string).
 * - `config_json`       - Remux configuration as a JSON C string.
 * - `progress_callback` - Called with `(json_event, file_index)` for every
 *                         progress event. May be `NULL` to suppress events.
 * - `file_index`        - Opaque index passed through to the callback so
 *                         callers can correlate events to files.
 * - `error_out`         - On error, receives a heap-allocated error message.
 *                         The caller must free it with `remux_free_string`.
 *                         May be `NULL` if the caller does not need it.
 *
 * # Returns
 *
 * A JSON string describing the result (input path, output files, errors).
 * The caller **must** free the returned string with `remux_free_string`.
 * Returns `NULL` on unrecoverable error (check `*error_out`).
 *
 * # Safety
 *
 * - `ubv_path` must be either null or a valid NUL-terminated UTF-8 C string.
 * - `config_json` must be either null or a valid NUL-terminated UTF-8 C string.
 * - `error_out` must be either null or point to a valid `*mut c_char` location.
 * - `progress_callback`, if provided, must be safe to call from any thread.
 */
char *remux_process_file(const char *ubv_path,
                         const char *config_json,
                         void (*progress_callback)(const char*, int32_t),
                         int32_t file_index,
                         char **error_out);

/**
 * Parse a `.ubv` file and produce a gzip-compressed JSON diagnostics file
 * at `<ubv_path>.json.gz`.
 *
 * # Parameters
 *
 * - `ubv_path`  - Path to the `.ubv` file (UTF-8 C string).
 * - `error_out` - On error, receives a heap-allocated error message.
 *                 The caller must free it with `remux_free_string`.
 *                 May be `NULL`.
 *
 * # Returns
 *
 * A JSON string `{"output_path":"..."}` on success. The caller **must**
 * free the returned string with `remux_free_string`.
 * Returns `NULL` on error (check `*error_out`).
 *
 * # Safety
 *
 * - `ubv_path` must be either null or a valid NUL-terminated UTF-8 C string.
 * - `error_out` must be either null or point to a valid `*mut c_char` location.
 */
char *remux_produce_diagnostics(const char *ubv_path, char **error_out);

/**
 * Parse a `.ubv` file and return its structure as a JSON string.
 *
 * # Parameters
 *
 * - `ubv_path`  - Path to the `.ubv` file (UTF-8 C string).
 * - `error_out` - On error, receives a heap-allocated error message.
 *                 The caller must free it with `remux_free_string`.
 *                 May be `NULL`.
 *
 * # Returns
 *
 * A JSON string containing the parsed UBV file structure. The caller
 * **must** free the returned string with `remux_free_string`.
 * Returns `NULL` on error (check `*error_out`).
 *
 * # Safety
 *
 * - `ubv_path` must be either null or a valid NUL-terminated UTF-8 C string.
 * - `error_out` must be either null or point to a valid `*mut c_char` location.
 */
char *remux_ubv_info(const char *ubv_path, char **error_out);

/**
 * Extract a JPEG thumbnail from the first video frame of an MP4 file.
 *
 * # Parameters
 *
 * - `mp4_path`    - Path to the MP4 file (UTF-8 C string).
 * - `output_path` - Where to write the JPEG thumbnail (UTF-8 C string).
 * - `max_width`   - Maximum thumbnail width in pixels.
 * - `error_out`   - On error, receives a heap-allocated error message.
 *                   The caller must free it with `remux_free_string`.
 *                   May be `NULL`.
 *
 * # Returns
 *
 * `0` on success, non-zero on error (check `*error_out`).
 *
 * # Safety
 *
 * - `mp4_path` and `output_path` must be valid NUL-terminated UTF-8 C strings.
 * - `error_out` must be either null or point to a valid `*mut c_char` location.
 */
int32_t remux_extract_thumbnail(const char *mp4_path,
                                const char *output_path,
                                uint32_t max_width,
                                char **error_out);

/**
 * Extract the 12-character uppercase hex MAC address from a UBV filename.
 *
 * Returns a heap-allocated string on success, `NULL` if no MAC was found.
 * The caller **must** free the returned string with `remux_free_string`.
 *
 * # Safety
 *
 * `filename` must be either null or a valid NUL-terminated UTF-8 C string.
 */
char *remux_extract_mac(const char *filename);

/**
 * Extract the unix-milliseconds timestamp from a UBV filename as a string.
 *
 * Returns a heap-allocated string on success, `NULL` if no timestamp was
 * found. The caller **must** free the returned string with
 * `remux_free_string`.
 *
 * # Safety
 *
 * `filename` must be either null or a valid NUL-terminated UTF-8 C string.
 */
char *remux_extract_timestamp(const char *filename);

/**
 * Check whether a UBV filename indicates a low-resolution recording.
 *
 * Returns `1` if the filename contains `_2_rotating_` or `_timelapse_`
 * (case-insensitive), `0` otherwise.
 *
 * # Safety
 *
 * `filename` must be either null or a valid NUL-terminated UTF-8 C string.
 */
int remux_is_low_res_filename(const char *filename);

/**
 * Load the cameras registry from the platform-specific application data
 * directory.
 *
 * Returns a JSON string `{"cameras":[...]}`. If the file does not exist or
 * cannot be read, returns `{"cameras":[]}`.
 *
 * The caller **must** free the returned string with `remux_free_string`.
 */
char *remux_load_cameras(void);

/**
 * Save the cameras registry to the platform-specific application data
 * directory.
 *
 * # Parameters
 *
 * - `cameras_json` - JSON string `{"cameras":[{"mac":"...","name":"..."},
 *   ...]}`.
 * - `error_out`    - On error, receives a heap-allocated error message. May
 *   be `NULL`.
 *
 * # Returns
 *
 * `0` on success, non-zero on error.
 *
 * # Safety
 *
 * - `cameras_json` must be either null or a valid NUL-terminated UTF-8 C
 *   string.
 * - `error_out` must be either null or point to a valid `*mut c_char`
 *   location.
 */
int remux_save_cameras(const char *cameras_json, char **error_out);

/**
 * Process a single `.ubv` file (with context pointer for callbacks).
 *
 * This is identical to `remux_process_file` except the callback receives an
 * additional `*mut c_void` context pointer, allowing callers (e.g. Swift) to
 * pass closure context without using globals.
 *
 * # Safety
 *
 * Same requirements as `remux_process_file`, plus `context` is passed
 * through opaquely to the callback and must remain valid for the duration of
 * the call.
 */
char *remux_process_file_ctx(const char *ubv_path,
                             const char *config_json,
                             void (*progress_callback)(const char*, int, void*),
                             int file_index,
                             void *context,
                             char **error_out);

/**
 * Free a string that was returned by one of the `remux_*` functions.
 *
 * Passing `NULL` is safe and has no effect.
 *
 * # Safety
 *
 * `s` must be either null or a pointer previously returned by one of the
 * `remux_*` functions in this library. Each pointer must only be freed once.
 */
void remux_free_string(char *s);

#endif  /* REMUX_FFI_H */
